// import {IHotelService} from '../hotelService.model';
//
// export const SERVICES: IHotelService[] = [
//   {
//     codeService: 'DV-0001',
//     nameService: 'Villa',
//     areaUsing: 200,
//     rentalFee: 1500,
//     maxOccupancies: 6,
//     rentalType: 'Full day',
//     roomStandard: 'Deluxe',
//     facilities: 'Full',
//     numberOfFloor: 2,
//     areaSwimmingPool: 20,
//     freeService: '',
//   },
//   {
//     codeService: 'DV-0002',
//     nameService: 'House',
//     areaUsing: 150,
//     rentalFee: 800,
//     maxOccupancies: 6,
//     rentalType: 'Full day',
//     roomStandard: 'Deluxe',
//     facilities: 'Full',
//     numberOfFloor: 1,
//     areaSwimmingPool: 0,
//     freeService: '',
//   },
//   {
//     codeService: 'DV-0003',
//     nameService: 'Room',
//     areaUsing: 50,
//     rentalFee: 300,
//     maxOccupancies: 2,
//     rentalType: 'Full day',
//     roomStandard: '',
//     facilities: '',
//     numberOfFloor: 0,
//     areaSwimmingPool: 0,
//     freeService: 'Drinking bottles per night',
//   },
// ];
